# Generated by Django 4.2.4 on 2023-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAdminSide', '0002_donardb_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipient_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Age', models.IntegerField(blank=True, null=True)),
                ('R_Mobile', models.IntegerField(blank=True, null=True)),
                ('R_Blood_Group', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Email', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Place', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Profile_Image', models.ImageField(blank=True, null=True, upload_to='r_images')),
            ],
        ),
    ]
