# Generated by Django 4.2.4 on 2023-12-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAdminSide', '0003_recipientdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientdb',
            name='R_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
