# Generated by Django 4.2.4 on 2023-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAdminSide', '0004_recipientdb_r_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donardb',
            name='Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
