# Generated by Django 4.2.4 on 2023-12-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAdminSide', '0005_donardb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientdb',
            name='R_Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
